name = "From Scratch"
author = "copygirl"
version = "0.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28503de81dd588ef9f9e208fe4254d322e59207c363a951e1cd5cfa37d6d31df"

[versions]
forge = "36.2.8"
minecraft = "1.16.5"
