name = "From Scratch"
author = "copygirl"
version = "0.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62d7553b81490b0d9eb85b5267d6f1c93c218883ea59db5d327f77aceb031726"

[versions]
forge = "36.2.8"
minecraft = "1.16.5"
