name = "From Scratch"
author = "copygirl"
version = "0.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3eeb6df947aeb91c6cb38444db8d710fea71b567b543ea43ad6e6bbb5c1ae7a"

[versions]
forge = "36.2.8"
minecraft = "1.16.5"
