name = "Project Red - Core"
filename = "ProjectRed-1.16.5-4.11.0-beta-0-core.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/382/ProjectRed-1.16.5-4.11.0-beta-0-core.jar"
hash-format = "murmur2"
hash = "3406386670"

[update]
[update.curseforge]
file-id = 3459382
project-id = 228702
release-channel = "beta"
